### PR TITLE
docs: broken link to systemd exporter on docs

### PR DESCRIPTION
**Pull request by jlosito**
This is a follow up to PR #102 .

### CODE REVIEW

**Review by gardar — APPROVED** [review]
Thanks!

**Comment by jlosito** [comment]
@gardar the step that failed apart of the workflow looks to be unrelated to this change. Is there anything I need to do to get this change merged?

**Comment by gardar** [comment]
The PR title should be in the format of `fix: ` but otherwise it looks good.

In regards to the ansible-lint issue, I've proposed a fix in #106

**Comment by gardar** [comment]
Please rebase

**Comment by gardar** [comment]
Mind rebasing again? ansible-lint v6.16.1 update arrived this morning which caused additional lint errors, fixed in #109

**Comment by jlosito** [comment]
@gardar I've rebased again, and now the linter check is passing.

**Pull request merged**
