### PR TITLE
docs: add argument specs to roles

### PR DESCRIPTION
**Pull request by gardar**
Enables parameter validation in roles and opens up the possibility to auto generate docs with [antsibull-docs](https://github.com/ansible-community/antsibull-docs/)

### CODE REVIEW

**Comment by paulfantom** [comment]
Are those files something that could be generated from `defaults.yaml` or would we need to remember to change them when `defaults.yaml` are changed?

**Comment by gardar** [comment]
Unfortunately they are managed completely separate from the defaults. Here's a discussion on the topic, but sadly it didn't go anywhere. https://github.com/ansible/ansible/issues/77664
We could go the same route as the OP in that issue and have a [script](https://github.com/nkakouros-original/ansible-role-easyrsa/blob/master/meta/generate_defaults.py) that auto generates the defaults from the argument specs.

With that being said, you would discover pretty quickly when they are missing because the role is validated against the argument specs and you will get an error if you supply incorrect parameters to the role.

**Comment by gardar** [comment]
We can however stop updating the readme and perhaps remove most of it, because docs can be auto generated from the argument specs.

**Comment by paulfantom** [comment]
> With that being said, you would discover pretty quickly when they are missing because the role is validated against the argument specs and you will get an error if you supply incorrect parameters to the role.

That makes sense. Especially when we have a validation check in CI.

**Review by paulfantom — APPROVED** [review]

**Comment by towolf** [comment]
@gardar can't use 0.1.4 due to this:
image

**Comment by gardar** [comment]
Thanks for the heads up @towolf I've pushed a fix here: #50

**Pull request merged**
