### PR TITLE
enhancement: Add time_intervals to AlertManager

### PR DESCRIPTION
**Pull request by rezizter**

### CODE REVIEW

**Comment by rezizter** [comment]
Add this feature: https://github.com/prometheus-community/ansible/issues/235

**Comment by gardar** [comment]
Thanks! Can you add it to the molecule test as well?

**Comment by rezizter** [comment]
> Thanks! Can you add it to the molecule test as well? And also a version check, the option was introduced in version 0.22.0 [prometheus/alertmanager#2393](https://github.com/prometheus/alertmanager/pull/2393)

Thank you. I have added the test. I have not worked with versions, let me see what I can add to preflights and push the changes.

**Review by gardar — APPROVED** [review]
LGTM!

**Pull request merged**
