### PR TITLE
fix: dont use Yum/Rpm task when packages are already installed

### PR DESCRIPTION
**Pull request by avdland**
This should fix issue #225

### CODE REVIEW

**Review by SuperQ — CHANGES_REQUESTED** [review]
This basically bypasses the real functionality of `ansible.builtin.package`. Rather than have a hacky workaround, we should probably switch to `ansible.builtin.yum` directly. This would allow tweaking the offline behavior with [controlling the metadata update flags](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/yum_module.html#parameter-cacheonly).

**Comment by gardar** [comment]
> This basically bypasses the real functionality of `ansible.builtin.package`. Rather than have a hacky workaround, we should probably switch to `ansible.builtin.yum` directly. This would allow tweaking the offline behavior with [controlling the metadata update flags](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/yum_module.html#parameter-cacheonly).

Agreed, but there is no need to switch to the yum module, the package module is actually just a proxy on top of the yum module, which means you can pass any of the yum module parameters to the package module

**Comment by avdland** [comment]
While testing, I had set cacheonly to true, but then it complained that the cache was empty, and the task would still fail...

**Comment by avdland** [comment]
But even if there was a parameter for the package module, there is no way I can set it outside of the playbook.

**Comment by avdland** [comment]
It seems that the `disablerepo` parameter does exactly what I want. I've added a new variable, `node_exporter_offline`, which then disables the repos if true.

**Comment by avdland** [comment]
I do think the previous commit https://github.com/prometheus-community/ansible/commit/b41c938919a749c9adcdeba6b29f552ae6cca531 is a better solution though... we shouldnt even have to run yum commands if the package is already installed

**Comment by SuperQ** [comment]
IMO this is a bug in Ansible's package module. It should not need to update caches or activate yum with `state: present`.

**Comment by avdland** [comment]
created new issue: https://github.com/ansible/ansible/issues/81847

**Comment by gardar** [comment]
https://github.com/prometheus-community/ansible/issues/225#issuecomment-2419535914

**Pull request closed without merging**
