### PR TITLE
fix: Remove unnecessary dependency on jmespath

### PR DESCRIPTION
**Pull request by flowerysong**
This is straightforward manipulation to do with standard Jinja features, there's no need to use a non-default library.

### CODE REVIEW

**Comment by SuperQ** [comment]
CC @gardar

**Comment by SuperQ** [comment]
Looks like the lint issue is unrelated. Looking into it.

**Comment by gardar** [comment]
Nice catch, LGTM!

**Review by gardar — APPROVED** [review]

**Comment by gardar** [comment]
@flowerysong please rebase

**Review by SuperQ — APPROVED** [review]

**Comment by flowerysong** [comment]
Test failures look unrelated.

Tests against Ansible 2.9 are failing because Ansible 2.9 reached EOL last May and is missing many collection features (like support for [git dependencies in requirements.yml](https://github.com/prometheus-community/ansible/blob/a0eaafd39e0da5411d1e9f271ad77f80e9a8590b/requirements.yml#L3-L4).)

The 2.12 failure was API rate limiting:
```
TASK [prometheus.prometheus.prometheus : Discover latest version] **************
fatal: [almalinux-8]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'url'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Received HTTP error for https://api.github.com/repos/prometheus/prometheus/releases/latest : HTTP Error 403: rate limit exceeded. Received HTTP error for https://api.github.com/repos/prometheus/prometheus/releases/latest : HTTP Error 403: rate limit exceeded"}
```

**Comment by SuperQ** [comment]
Actually, the 2.9 failure is because we started fetching things from git instead of galaxy. The old version does not support fetching from git.

**Comment by flowerysong** [comment]
> Actually, the 2.9 failure is because we started fetching things from git instead of galaxy. The old version does not support fetching from git.

That's what I said.

There's a decent chance that my change will also legitimately fail on 2.9; automatic generator unrolling wasn't added until 2.10.

**Comment by gardar** [comment]
2.9 test has been fixed by #37

**Pull request merged**
