### PR TITLE
fix: Improve apt facts install

### PR DESCRIPTION
**Pull request by SuperQ**
Reduce the number of packages installed by the apt package facts preflight by using the apt module and disabling recommends packages.

### CODE REVIEW

**Review by gardar — COMMENTED** [review]
There's no need to switch the task over to `apt` as the `package` module is actually just a proxy for apt or whatever package manager is present.

With that being said, the way the task is configured right now it actually never runs on any non apt systems.
I think we should make sure the task also installs the required dependencies for other distros, even though we don't run tests against them. it looks like suse requires python3-rpm and gentoo needs qlist.

**Comment by SuperQ** [comment]
Except we do need to switch to `apt`, since `package` doesn't expose "install_recommends" as a parameter.

**Comment by gardar** [comment]
That is true but it simply passes the parameters down to the underlying module that it's proxy-ing.
https://docs.ansible.com/ansible/latest/collections/ansible/builtin/package_module.html#id1

**Review by gardar — COMMENTED** [review]
Might be good to only pass the `install_recommends` parameter if `ansible_pkg_mgr` is `apt` else omit it to avoid future issues.

**Pull request closed without merging**
