### PR TITLE
feat: Add prometheus_scrape_config feature

### PR DESCRIPTION
**Pull request by romanbilenko174**
Added prometheus_scrape_config_files support as mentioned in https://github.com/prometheus-community/ansible/issues/145

### CODE REVIEW

**Comment by Lycowolf** [comment]
Hi, I am currently being blocked by #145 and would like to have this fixed.

I read the PR and I think there's nothing wrong with it technically. Because the PR is more than 2 months old, I am volunteering to take over this PR and drive it to finsh. IIUC the only missing piece is the missing sign-off, but (as I am not the author), I can't really provide that.

Is there a way forward? Or do I have to write my own version and submit that?

**Comment by gardar** [comment]
> Is there a way forward? Or do I have to write my own version and submit that?

Yes that would be the correct way for you to "take over".


@romanbilenko174 ping
> Can you please fix the DCO?

**Comment by Lycowolf** [comment]
My version of this is https://github.com/prometheus-community/ansible/pull/292

**Comment by gardar** [comment]
superseded by #368

**Pull request closed without merging**
