### PR TITLE
enhancement: add `skip_install` variables to various roles

### PR DESCRIPTION
**Pull request by chrisbra**
This is similar to prometheus_skip_install variable and does what the name says: when set, it won't try to re-download alertmanager binaries

thanks for considering

### CODE REVIEW

**Comment by gardar** [comment]
Wouldn't it make sense to have `skip_install` variables for all of the roles?

**Comment by chrisbra** [comment]
yes, quite possible

**Comment by chrisbra** [comment]
let me amend the pr with additional `skip_install` variables for the other roles.

**Comment by chrisbra** [comment]
should be there now

**Review by gardar — CHANGES_REQUESTED** [review]
Looks like we're not quite there yet, please take a look at the failures in the tests.

**Comment by chrisbra** [comment]
yeah, looks like I messed up one of those conditions. Should be fixed now (and will re-push with my `Sign-Offed By` added

**Comment by chrisbra** [comment]
do you want me to rebase on top of main?

**Review by gardar — APPROVED** [review]
LGTM!

**Review by SuperQ — APPROVED** [review]

**Pull request merged**
