### PR TITLE
fix: policycoreutils python package name

### PR DESCRIPTION
**Pull request by mikaellanger**
I have a few legacy hosts with Centos 7 where trying to install python-policycoreutils fails.

At least in Centos 7 the packages is named policycoreutils-python, and finding no such package here either https://pkgs.org/download/python-policycoreutils

### CODE REVIEW

**Review by SuperQ — CHANGES_REQUESTED** [review]
Two things. This task is used in several roles, so should update all them.

I also think this is going to be a problem for redhat 8+, since this package has been renamed.

**Comment by SuperQ** [comment]
Hmm, I guess if python3 is a good enough signal, it should work.

**Comment by gardar** [comment]
The definition is present in these files:

https://github.com/prometheus-community/ansible/blob/d389ad29e203ed24aebb02796958837bdca6d35e/roles/prometheus/vars/main.yml#L12-L14
https://github.com/prometheus-community/ansible/blob/d389ad29e203ed24aebb02796958837bdca6d35e/roles/alertmanager/tasks/selinux.yml#L4-L6
https://github.com/prometheus-community/ansible/blob/d389ad29e203ed24aebb02796958837bdca6d35e/roles/node_exporter/tasks/selinux.yml#L4-L6

The package change came with python3 on redhat based platforms, that's why I thought the cleanest approach would be to make the conditional work on the python interpreter. (and yes you can blame me for the package name typo - whoops :) )

**Comment by mikaellanger** [comment]
Changed the other two places.

> The package change came with python3 on redhat based platforms, that's why I thought the cleanest approach would be to make the conditional work on the python interpreter.

Based on available packages I agree that seems to be correct, yes.

**Review by gardar — APPROVED** [review]

**Comment by gardar** [comment]
@mikaellanger please fix sign-off

**Review by SuperQ — APPROVED** [review]
Just need to fix the DCO.

**Comment by mikaellanger** [comment]
Done

**Pull request merged**
