### PR TITLE
fix: wrong snmp_exporter binary source path

### LINKED ISSUE #96: Unable to install snmp_node_exporter
Hi,

snmp_node_exporter install seems broken. The task `prometheus.prometheus.snmp_exporter : Download snmp_exporter binary to local folder` download the binary to a "random" file (`"dest": "/tmp/8490f100-eb94-11ea-87ba-182377c269c8"`).
The task `prometheus.prometheus.snmp_exporter : Unpack snmp_exporter binary` want to unpack file from `'/tmp/snmp_exporter-0.19.0.linux-amd64.tar.gz'`.

```
TASK [prometheus.prometheus.snmp_exporter : Download snmp_exporter binary to local folder] ****************************************************************************************************************************************************************************************************************************************************
vendredi 05 mai 2023  16:01:30 +0200 (0:00:00.050)       0:01:17.256 ********** 
vendredi 05 mai 2023  16:01:30 +0200 (0:00:00.050)       0:01:17.256 ********** 
ok: [hnld-ptls-amazonl2-prometheus-dev01 -> localhost] => {
    "attempts": 1,
    "changed": false,
    "checksum_dest": "ff333c8409a9587720d2b55c31335f2290bc46c7",
    "checksum_src": "ff333c8409a9587720d2b55c31335f2290bc46c7",
    "dest": "/tmp/8490f100-eb94-11ea-87ba-182377c269c8",
    "elapsed": 1,
    "gid": 1000,
    "group": "seb",
    "md5sum": "5bccac10fb0d258148c488c30c786eca",
    "mode": "0644",
    "owner": "seb",
    "size": 7313658,
    "src": "/home/seb/.ansible/tmp/ansible-tmp-1683295290.88605-270186-112912528244913/tmpetxjw74o",
    "state": "file",
    "status_code": 200,
    "uid": 1000,
    "url": "https://github.com/prometheus/snmp_exporter/releases/download/v0.19.0/snmp_exporter-0.19.0.linux-amd64.tar.gz"
}

MSG:

OK (7313658 bytes)

TASK [prometheus.prometheus.snmp_exporter : Unpack snmp_exporter binary] **********************************************************************************************************************************************************************************************************************************************************************
vendredi 05 mai 2023  16:01:32 +0200 (0:00:01.678)       0:01:18.935 ********** 
vendredi 05 mai 2023  16:01:32 +0200 (0:00:01.679)       0:01:18.935 ********** 
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [hnld-ptls-amazonl2-prometheus-dev01 -> localhost]: FAILED! => {
    "changed": false
}

MSG:

Could not find or access '/tmp/snmp_exporter-0.19.0.linux-amd64.tar.gz' on the Ansible Controller.
If you are using a module and expect the file to exist on the remote, see the remote_src option

```

### PR DESCRIPTION
**Pull request by sebbbastien**
This is a PR to fix #96

Not familiar with contributions and PR, please be indulgent

### CODE REVIEW

**Comment by SuperQ** [comment]
Hmm, I think there's more to fix than this.

**Comment by sebbbastien** [comment]
> Hmm, I think there's more to fix than this.

Do you mean, this error is present on other installations, or, there is more to fix for snmp_exporter install?


To fix the error during snmp_exporter install, the change is enough on my side.


Is it possible to write a molecule test to check this issue?

**Comment by gardar** [comment]
The problem is actually just that the `dest` from `get_url` is missing the trailing slash.

https://github.com/prometheus-community/ansible/blob/26d2f998573819faa150deaf8806175cd53e8a30/roles/snmp_exporter/tasks/install.yml#L2-L9

Should be either

```diff
  ansible.builtin.get_url:
    url: "{{ snmp_exporter_binary_url }}"
-    dest: "/tmp"
+    dest: "/tmp/"
    checksum: "sha256:{{ snmp_exporter_checksum }}"
    mode: 0644
  register: _download_binary
```

or to be consistent with the other roles:

```diff
  ansible.builtin.get_url:
    url: "{{ snmp_exporter_binary_url }}"
-    dest: "/tmp"
+    dest: "/tmp/snmp_exporter-{{ snmp_exporter_version }}.linux-{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}.tar.gz"
    checksum: "sha256:{{ snmp_exporter_checksum }}"
    mode: 0644
  register: _download_binary
```

**Comment by SuperQ** [comment]
This should be fixed by https://github.com/prometheus-community/ansible/pull/204.

**Comment by SuperQ** [comment]
Fixed in #204

**Pull request closed without merging**
