### PR TITLE
fix: Install package fact dependencies needs to be run as root

### PR DESCRIPTION
**Pull request by JonathanMbt**

### CODE REVIEW

**Comment by gardar** [comment]
Thanks! I see that this issue is also present in other roles, do you mind adding the fix to them as well?
And please rebase, the CI was failing due to EOL platforms which I just fixed #53

**Comment by JonathanMbt** [comment]
No problem, all roles should be fixed now.

**Review by gardar — APPROVED** [review]

**Comment by JonathanMbt** [comment]
yes, I will do that in the next days

**Comment by SuperQ** [comment]
Ping

This needs a DCO sign-off. You can use `git commit -s --amend` to add it.

**Comment by JonathanMbt** [comment]
Yep completely forgot about it, I do it this evening.

**Pull request merged**
